# Generated by Django 2.1.2 on 2018-10-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('mobile_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=100)),
                ('salary', models.IntegerField()),
                ('comm', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
